version: 0.2

env:
  parameter-store:
    DOCKER_USER: "/CodeBuild/applications/expense-tracker-app/docker/user"
    DOCKER_PASSWORD: "/CodeBuild/applications/expense-tracker-app/docker/password"

phases:
  install:
    commands:
      - echo "Copying settings.xml from S3"
      - aws s3 cp s3://budgetapp-configuration/maven/settings.xml /root/.m2/
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 667631227859.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Running maven package
      - mvn clean install -Dmaven.test.skip
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - docker build -t budgetapp:latest .
      - docker tag budgetapp:latest 667631227859.dkr.ecr.us-east-1.amazonaws.com/budgetapp:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 667631227859.dkr.ecr.us-east-1.amazonaws.com/budgetapp:latest
cache:
  paths:
    - '/root/.m2/**/*'
artifacts:
  files:
    - appspec.yml
    - scripts/kill_container.sh
    - scripts/load_image.sh
    - scripts/start_container.sh
    - scripts/delete_previous_version.sh
  discard-paths : yes
  # base-directory : docker_build