spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: none
  #    database: h2
  #    properties:
#      hibernate:
#        hbm2ddl:
#          auto: create-only
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: embedded